# Site settings
title: 'Max Humber'
description:

author: Max Humber
email: max.humber@gmail.com
twitter_username: maxhumber
github_username: maxhumber

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://maxhumber.com' # the base hostname & protocol for your site

google_analytics_id: UA-89691472-1

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:title

sass:
    style: compressed

exclude: [vendor]
